### ISSUE TITLE
Add logrotate config files to `deploy/logrotate`

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dmqnode#21] opened 2018-01-31 13:09 UTC
For example, see https://github.com/sociomantic/dhtnode/tree/master/deploy/logrotate.

**Comment by david-eckardt-sociomantic** [comment] 2018-02-28 15:33
Duplicate of #23, which has been fixed.

**Closed by david-eckardt-sociomantic** 2018-02-28 15:33 UTC
Labels: res-duplicate
