### ISSUE TITLE
CI build failure with DMD=2.078.* DIST=xenial

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dmqnode#67] opened 2018-08-01 08:29 UTC
```
run build/production/tmp/test-dmqtest
integrationtest/ovfminimize/main.d(33): Deprecation: function ocean.transition.getMsg is deprecated - Use Exception.message() directly
integrationtest/ovfminimize/main.d(33): Deprecation: function ocean.transition.getMsg is deprecated - Use Exception.message() directly
[turtle    ] Early termination from '/home/travis/build/sociomantic-tsunami/dmqnode/build/production/tmp/sandbox-dmqnode-XXyET06W/bin/dmqnode --config=etc/config.ini', aborting.
./src/dmqnode/node/RequestHandlers.d(36): Deprecation: function swarm.neo.node.ConnectionHandler.ConnectionHandler.RequestMap.add is deprecated - Use addHandler instead
./src/dmqnode/node/RequestHandlers.d(38): Deprecation: function swarm.neo.node.ConnectionHandler.ConnectionHandler.RequestMap.add is deprecated - Use addHandler instead
./src/dmqnode/node/RequestHandlers.d(40): Deprecation: function swarm.neo.node.ConnectionHandler.ConnectionHandler.RequestMap.add is deprecated - Use addHandler instead
Aborted (core dumped)
```
This has failed twice in a row now.

**Comment by gavin-norman-sociomantic** [comment] 2018-08-01 08:34
Retriggering just that one job, it succeeded. Trying retriggering the whole build now.

**Comment by gavin-norman-sociomantic** [comment] 2018-08-01 08:45
DMD=2.078.* DIST=xenial F=production succeeded, but DMD=2.078.* DIST=xenial F=devel failed, this time. Seems genuinely flaky.

**Comment by nemanja-boric-sociomantic** [comment] 2018-08-09 12:47
Duplicate of #65

**Closed by nemanja-boric-sociomantic** 2018-08-09 12:47 UTC
Labels: type-bug
